public class TodayTasks {
    public TodayTasks(){
        takeShower();
        havingBF();
        carRepair();
        datewithGF();
    }
    public static void takeShower(){
        system.debug('i am taking shower');
    }
    public static void havingBF(){
        system.debug('i am having BF');
    }
     @future    
    public static void carRepair(){
        system.debug('Car has been given for service');
    }
    public static void datewithGF(){
        system.debug('I am in Theatre with Gf');
    }
}